### ISSUE TITLE
ToDo field "completed"? Or archived. Something to check it off without deleting it

### ISSUE THREAD

**Issue by rlane85** [Blane245/lane-db#25]
In my original mock-up of a todo list, it had the feature to strikethrough a todo to indicate it had been completed. 

an easy solution with the current framework would be to set the priority status to 0

a slightly more involved implementation of the "completed" status of a todo would be to add the "completed" field in the todo database. either boolen, enum, or a string. 
e.g. true/false, "completed"/"not completed"/"not specified", or a simple string. I think a bool is probably the safest option, but probably best to allow null in the db

**Comment by Blane245** [comment]
The varuous flags that you mention are ways that the client can process the display. 

Note that todo status takes on three values. Based on these values you could color or otherwise markup by the todo text. Using these three values you can filter and sort. 
I would prefer not to change the priority when the status changes. This would kill the original priority. Here are a couple of use cases:
1. Show all todos (table with text, priority, status, duedate, id, create and updated dates are available too).
2. Sort list by priority (ascending descending). User click on priority header widget or say "sort todo list by priority (ascending, descending)
3. Show only incomplete todos (status is toto or inprogress)
4. Mark a doto inprogress or complete (todo must be visible then the todo status is changed, maybe affecting its visibility in the list)
5. Change a todo priority to a new number (todo must be visible, the todos priority is changed  (and may cause list to resort on priority)
6. Delete a todo (must be visible then todo is deleted and list is displayed based on sort and filters)

**Comment by rlane85** [comment]
Ok, I didn't really the status field behaved this way. My bad! your mermaid docs actually enlightened me. So status is type enum with the possible options of `["todo", "inprogress", "done"]`
👍

**Comment by Blane245** [comment]
You don't have to use inprogress if you don't want to. I added it for completeness. When a todo is created it's in the todo status.
